package utilities;

public enum  EventTask {
    TABS_LISTS_FRAGMENT_MOVE_TO_TODO_LIST, TABS_LISTS_FRAGMENT_MOVE_TO_DOING_LIST, TABS_LISTS_FRAGMENT_MOVE_TO_DONE_LIST,
    TABS_LISTS_UPDATE_DATA_SOURCE, LIST_DOING_FRAGMENT_UPDATE_COUNTDOWN;
}
